---
version: "3.7"

volumes:
    db:
    overlay:
        driver: local
        driver_opts:
            type: overlay
            device: overlay
            o: lowerdir=${PWD}/../..,upperdir=${PWD}/../../../volumes/unittest/upper,workdir=${PWD}/../../../volumes/unittest/work
    
services:
    dut:
        build:
            context: ./dut
            args:
                WWW_DATA_UID: 1000
        
        #ports:
            #- 8082:80
        volumes:
            - "overlay:/var/www/pk"
            - "./coverage-report:/report"
        environment:
            GITHUB_DEBUG_UID: 1000
            #DEBUG_VARS: "idekey=XDEBUG_ECLIPSE remote_host=172.17.0.1 remote_connect_back=false xdebug.remote_enable=true remote_log=/tmp/xdebug.log"
            #FILTER_STRING: "--filter testGetImage src/PartKeepr/ImageBundle/Tests/ImageControllerTest.php"
    
    mariadb:
        image: mariadb:10.1
        volumes:
            - db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: partkeepr
            MYSQL_PASSWORD: partkeepr
            MYSQL_DATABASE: partkeepr_test
    
            
