name: Docker Image Creation

on: 
  push:

jobs:

  create-docker-images:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetch git tags
      run: git fetch --unshallow origin +refs/tags/*:refs/tags/*
      
    - name: Build the base docker image
      run: docker build docker/base --file docker/base/Dockerfile --tag docker.pkg.github.com/christianlupus/partkeepr/base:latest
    - name: Tag the base docker image with git hash
      run: docker tag docker.pkg.github.com/christianlupus/partkeepr/base:latest docker.pkg.github.com/christianlupus/partkeepr/base:$(git describe)
    - name: Deploy the base docker images
      run: |
        docker login -u christianlupus -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
        docker push docker.pkg.github.com/christianlupus/partkeepr/base:latest
        docker push docker.pkg.github.com/christianlupus/partkeepr/base:$(git describe)
      
    - name: Check for production image
      run: |
        docker/production/check-build.sh
    
    - name: Build development image
      run: docker build docker/development/app --file docker/development/app/Dockerfile --tag docker.pkg.github.com/christianlupus/partkeepr/development:latest --build-arg SRC_IMAGE=docker.pkg.github.com/christianlupus/partkeepr/base:$(git describe)
    - name: Tag the development docker image with git hash
      run: docker tag docker.pkg.github.com/christianlupus/partkeepr/development:latest docker.pkg.github.com/christianlupus/partkeepr/development:$(git describe)
    - name: Deploy the development docker images
      run: |
        docker login -u christianlupus -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
        docker push docker.pkg.github.com/christianlupus/partkeepr/development:latest
        docker push docker.pkg.github.com/christianlupus/partkeepr/development:$(git describe)

