name: Docker Image Creation

on: 
  push:

jobs:

  create-base:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build docker/base --file Dockerfile --tag docker.pkg.github.com/christianlupus/partkeepr/base:latest
    - name: Tag the Docker image with date
      run: docker tag docker.pkg.github.com/christianlupus/partkeepr/base:latest docker.pkg.github.com/christianlupus/partkeepr/base:$(git describe)
    - name: Deploy the Docker image
      run: |
        docker login -u christianlupus -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
        docker push docker.pkg.github.com/christianlupus/partkeepr/base:latest
        docker push docker.pkg.github.com/christianlupus/partkeepr/base:$(git describe)
      
