name: Docker Image Creation

on: 
  push:
    branches:
      - master
    tags:
      - '**'

jobs:

  create-base-docker-image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetch git tags
      run: git fetch --unshallow origin +refs/tags/*:refs/tags/*
      
    - name: Build the base docker image
      run: docker build docker/base --file docker/base/Dockerfile --tag partkeepr/base:latest
    - name: Tag the base docker image with git hash
      run: docker tag partkeepr/base:latest partkeepr/base:$(git describe)
    - name: Deploy the base docker images
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
        docker push partkeepr/base:latest
        docker push partkeepr/base:$(git describe)
      
  create-production-docker-image:
    
    runs-on: ubuntu-latest
    needs: create-base-docker-image
    
    steps:
    - name: Check for production image
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
        docker/production/check-build.sh
    
  create-development-docker-image:
    
    runs-on: ubuntu-latest
    needs: create-base-docker-image
    
    steps:
    - name: Build development image
      run: docker build docker/development/app --file docker/development/app/Dockerfile --tag partkeepr/development:latest --build-arg SRC_IMAGE=partkeepr/base:$(git describe)
    - name: Tag the development docker image with git hash
      run: docker tag partkeepr/development:latest partkeepr/development:$(git describe)
    - name: Deploy the development docker images
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
        docker push partkeepr/development:latest
        docker push partkeepr/development:$(git describe)

